"""new rules #2

Revision ID: 00f6986ee383
Revises: 6ba39cca719d
Create Date: 2024-06-05 18:52:49.831008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00f6986ee383'
down_revision: Union[str, None] = '6ba39cca719d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('reports_place_id_fkey', 'reports', type_='foreignkey')
    op.drop_constraint('reports_user_id_fkey', 'reports', type_='foreignkey')
    op.create_foreign_key(None, 'reports', 'employees', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'reports', 'places', ['place_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.create_foreign_key('reports_user_id_fkey', 'reports', 'employees', ['user_id'], ['id'])
    op.create_foreign_key('reports_place_id_fkey', 'reports', 'places', ['place_id'], ['id'])
    # ### end Alembic commands ###
